access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://rivindupabasaraganegoda1:uBzV1Xc1sWUFYHPz@cluster0.bvyfepr.mongodb.net/test
logging:
  level:
    org.springframework.security: DEBUG

